force-app/main/default/objects/Donor__c/Donor__c.object-meta.xml
<CustomObject>
    <label>Donor</label>
    <nameField>
        <label>Donor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donor__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula>IF(
    Total_Donations__c &gt;= 500000,
    &quot;⭐⭐⭐⭐⭐&quot;,
    IF(
        Total_Donations__c &gt;= 300000,
        &quot;⭐⭐⭐⭐&quot;,
        IF(
            Total_Donations__c &gt;= 100000,
            &quot;⭐⭐⭐&quot;,
            IF(
                Total_Donations__c &gt;= 50000,
                &quot;⭐⭐&quot;,
                IF(
                    Total_Donations__c &gt; 0,
                    &quot;⭐&quot;,
                    &quot;&quot;
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DonorListController.cls
/**
 * @description       : 
 * @author            : Srividhya
 * @group             : 
 * @last modified on  : 07-21-2026
 * @last modified by  : Srividhya
**/
public with sharing class DonorListController {
     @AuraEnabled(cacheable=true)
    public static List<Donor__c> getDonors() {

        return [
            SELECT Id,
                   Name,
                   Rating__c
            FROM Donor__c
            ORDER BY Name
            LIMIT 100
        ];
    }

}